cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    A12345:
      name: Demo
      password: $2b$12$Li3wlWS2RR7DVutoc3lqzORltAJM.85EDymJkHiuPzuFLBImpZKfm
      email: demo@example.com
preauthorized:
  emails: []
